# Generated by Django 4.0.4 on 2022-05-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ctegory',
            new_name='category',
        ),
    ]
